# -*- coding: utf-8 -*-
"""Lab1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v_464uH-87V_DHxyZNfASns3V5uKpdfD
"""

import zipfile

# Unzip the diamonds.csv.zip file
with zipfile.ZipFile('/content/diamonds.csv.zip', 'r') as zip_ref:
    zip_ref.extractall('/content/')

print('diamonds.csv.zip unzipped to /content/diamonds.csv')

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# -----------------------------
# CRISP-DM Phase 1: Business Understanding
# Objective: Predict diamond price category (classification)
# -----------------------------

# -----------------------------
# CRISP-DM Phase 2: Data Understanding
# -----------------------------
df = pd.read_csv("/content/diamonds.csv")

# -----------------------------
# CRISP-DM Phase 3: Data Preparation
# -----------------------------

# Create a target variable by binning 'price' into categories
df['price_category'] = pd.cut(df['price'], bins=[0, 1000, 3000, 5000, 10000, df['price'].max()], labels=[0, 1, 2, 3, 4])
# Drop original 'price' column and unnecessary 'Unnamed: 0' column
df = df.drop(['price', 'Unnamed: 0'], axis=1)

# Encode categorical columns (cut, color, clarity)
le = LabelEncoder()
for col in ['cut', 'color', 'clarity']:
    df[col] = le.fit_transform(df[col])

# Separate features and target
X = df.drop("price_category", axis=1)
y = df["price_category"]

# Handle missing values (if any, though diamonds dataset is usually clean)
imputer = SimpleImputer(strategy="mean")
X = imputer.fit_transform(X)

# Feature Scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y # Stratify for classification tasks with binned categories
)

# -----------------------------
# CRISP-DM Phase 4: Modeling
# -----------------------------
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# -----------------------------
# CRISP-DM Phase 5: Evaluation
# -----------------------------
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("CRISP-DM Accuracy:", accuracy)

# -----------------------------
# CRISP-DM Phase 6: Deployment
# (Optional - Save the trained model)
# -----------------------------
# import joblib
# joblib.dump(model, "diamond_price_category_model.pkl")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# -----------------------------
# S - Sample
# -----------------------------
df = pd.read_csv("/content/diamonds.csv")

# -----------------------------
# E - Explore
# -----------------------------
# Create a target variable by binning 'price' into categories
df['price_category'] = pd.cut(df['price'], bins=[0, 1000, 3000, 5000, 10000, df['price'].max()], labels=[0, 1, 2, 3, 4])
# Drop original 'price' column and unnecessary 'Unnamed: 0' column
df = df.drop(['price', 'Unnamed: 0'], axis=1)

# Encode categorical columns (cut, color, clarity)
le = LabelEncoder()
for col in ['cut', 'color', 'clarity']:
    df[col] = le.fit_transform(df[col])

# -----------------------------
# M - Modify
# -----------------------------
X = df.drop("price_category", axis=1)
y = df["price_category"]

# Split the data
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# Handle missing values
imputer = SimpleImputer(strategy="mean")
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# -----------------------------
# M - Model
# -----------------------------
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# -----------------------------
# A - Assess
# -----------------------------
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("SEMMA Accuracy:", accuracy*100)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# -----------------------------
# KDD Step 1: Selection
# -----------------------------
df = pd.read_csv("/content/diamonds.csv")

# Create a target variable by binning 'price' into categories
df['price_category'] = pd.cut(df['price'], bins=[0, 1000, 3000, 5000, 10000, df['price'].max()], labels=[0, 1, 2, 3, 4])
# Drop original 'price' column and unnecessary 'Unnamed: 0' column
df = df.drop(['price', 'Unnamed: 0'], axis=1)

# -----------------------------
# KDD Step 2: Preprocessing
# -----------------------------
# Encode categorical columns (cut, color, clarity)
le = LabelEncoder()
for col in ['cut', 'color', 'clarity']:
    df[col] = le.fit_transform(df[col])

X = df.drop("price_category", axis=1)
y = df["price_category"]

# Handle missing values
imputer = SimpleImputer(strategy="mean")
X = imputer.fit_transform(X)

# -----------------------------
# KDD Step 3: Transformation
# -----------------------------
scaler = StandardScaler()
X = scaler.fit_transform(X)

# -----------------------------
# KDD Step 4: Data Mining
# -----------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# -----------------------------
# KDD Step 5: Interpretation
# -----------------------------
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("KDD Accuracy:", accuracy*100)