# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TNhoUglIPmVWxFEp2llWstNFCS3B4_I7
"""

import pandas as pd
import zipfile
import io

zip_file_path = '/content/diamonds.csv.zip'
csv_file_name = 'diamonds.csv'

# Open the ZIP file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # Check if the CSV file exists inside the ZIP
    if csv_file_name in zip_ref.namelist():
        # Extract the CSV file content
        with zip_ref.open(csv_file_name) as csv_file:
            # Read the CSV content into a pandas DataFrame
            df = pd.read_csv(csv_file)
            print(f"Successfully extracted and loaded '{csv_file_name}' into a DataFrame.")
            display(df.head())
    else:
        print(f"Error: '{csv_file_name}' not found inside '{zip_file_path}'.")

"""## Data Analysis"""

# Display DataFrame info to check data types and non-null values
print(df.info())

# Display descriptive statistics for numerical columns
display(df.describe())

# Check for missing values
print("\nMissing values per column:")
display(df.isnull().sum())

"""## Data Cleaning"""

# Drop the 'Unnamed: 0' column as it appears to be a redundant index
df = df.drop('Unnamed: 0', axis=1)
print("Dropped 'Unnamed: 0' column.")

# Identify and count rows where x, y, or z dimensions are 0
zero_dimension_rows = df[(df['x'] == 0) | (df['y'] == 0) | (df['z'] == 0)]
print(f"\nNumber of rows with x, y, or z equal to 0: {len(zero_dimension_rows)}")

# Remove rows where x, y, or z are 0 (as these are physically impossible for a diamond)
df = df[(df['x'] != 0) & (df['y'] != 0) & (df['z'] != 0)]
print("Removed rows where x, y, or z dimensions were 0.")

# Display the shape of the DataFrame after cleaning
print(f"\nNew DataFrame shape: {df.shape}")

# Display info and describe again to see the impact of cleaning
print("\nDataFrame info after cleaning:")
print(df.info())
print("\nDescriptive statistics after cleaning:")
display(df.describe())

"""## Data Type Conversion & Visualization"""

# Convert categorical columns to 'category' dtype
for col in ['cut', 'color', 'clarity']:
    df[col] = df[col].astype('category')

print("Converted 'cut', 'color', 'clarity' to categorical type.")
print("\nDataFrame info after type conversion:")
print(df.info())

"""## Further SQL Query: Average and Max Price by Cut and Color"""

import sqlite3

# Create a new in-memory SQLite database connection
conn_new_query = sqlite3.connect(':memory:')

# Load the original 'df' DataFrame into a new SQL table named 'diamonds_data'
df.to_sql('diamonds_data', conn_new_query, index=False, if_exists='replace')

# Define the new SQL query
sql_query_cut_color_price = """
SELECT
    cut,
    color,
    AVG(price) AS average_price,
    MAX(price) AS maximum_price,
    COUNT(*) AS number_of_diamonds
FROM
    diamonds_data
GROUP BY
    cut, color
ORDER BY
    average_price DESC;
"""

print("Executing the following SQL query on the 'diamonds_data' table:")
print(sql_query_cut_color_price)

# Execute the new SQL query
cut_color_price_results = pd.read_sql_query(sql_query_cut_color_price, conn_new_query)

# Display the results of the new query
print("\nResults of the new SQL query:")
display(cut_color_price_results)

# Close the connection
conn_new_query.close()
print("\nSQLite connection closed for this query.")

"""## Further SQL Query: Average and Max Carat by Clarity and Color"""

import sqlite3

# Create a new in-memory SQLite database connection for this specific query
conn_carat_query = sqlite3.connect(':memory:')

# Load the original 'df' DataFrame into a new SQL table named 'diamonds_carat_data'
df.to_sql('diamonds_carat_data', conn_carat_query, index=False, if_exists='replace')

# Define the new SQL query to get average and max carat by clarity and color
sql_query_clarity_color_carat = """
SELECT
    clarity,
    color,
    AVG(carat) AS average_carat,
    MAX(carat) AS maximum_carat,
    COUNT(*) AS number_of_diamonds
FROM
    diamonds_carat_data
GROUP BY
    clarity, color
ORDER BY
    average_carat DESC;
"""

print("Executing the following SQL query on the 'diamonds_carat_data' table:")
print(sql_query_clarity_color_carat)

# Execute the new SQL query
clarity_color_carat_results = pd.read_sql_query(sql_query_clarity_color_carat, conn_carat_query)

# Display the results of the new query
print("\nResults of the new SQL query:")
display(clarity_color_carat_results)

# Close the connection
conn_carat_query.close()
print("\nSQLite connection closed for this query.")

"""## Statistical Summary of Aggregated Price Data"""

# Display statistical summary of the aggregated price results
print("Statistical summary of 'cut_color_price_results':")
display(cut_color_price_results.describe())

"""## Export `cut_color_price_results` to CSV"""

# Export the DataFrame to a CSV file
output_csv_path = '/content/cut_color_price_results.csv'
cut_color_price_results.to_csv(output_csv_path, index=False)

print(f"DataFrame successfully exported to '{output_csv_path}'")